### ISSUE TITLE
Create structured changelogs

### ISSUE THREAD

**Issue by matthias-reis** [matthias-reis/rlsr#12]
... something like this: https://github.com/angular/angular/blob/master/CHANGELOG.md#400-rc3-2017-03-10

Sections:
- BREAKING CHANGES
- New Features
- Bug Fixes
- Performance Improvements
- Refactorings
- Reverted Changes
- Dependency Updates

**Comment by matthias-reis** [comment]
Created example:

# Changelog rlsr-1

## Version 1.1.2


### Dependency Updates

perf in *rlsr-1-1*: **perf booster**

fix in *rlsr-1-1*: **another patch**

feat in *rlsr-1-2*: **new line**


## Version 1.1.1


### Dependency Updates

perf in *rlsr-1-1*: **perf booster**

**Comment by HerrBertling** [comment]
Voll schön 😊 💚
