### ISSUE TITLE
breaking changes in irrelevant commits

### ISSUE THREAD

**Issue by Xiphe** [matthias-reis/rlsr#2]
The [angular-git-commit-guidelines](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines) are not clear about this, and neither is [semantic-release](https://github.com/semantic-release/semantic-release#default-commit-message-format)

But from my understanding, the guidelines support `BREAKING CHANGES` in `chore` commits, while [this implementation](https://github.com/matthias-reis/rlsr/blob/master/src/tools/get-parsed-commit-messages.js#L21) would skip these

**Comment by matthias-reis** [comment]
As discussed, I'll add this to the Readme.md - create a small FAQ section.

**Comment by Xiphe** [comment]
Again as we discussed today, since this is not clearly specced out in other tools, I'd consider this as fine until problems arise. Feel free to `wontfix` this from my pov.

To elaborate: We agreed that if you follow the guidelines, BREAKING changes can only happen when you introduce something that affects the API, and thinks that affect the api should never be commited as type `docs`, `chore` or `test`.
