### ISSUE TITLE
docs: previouslyUnreleased api is not documented

### ISSUE THREAD

**Issue by Xiphe** [matthias-reis/rlsr#4]
From reading the readme it's not clear to me how and why I'm supposed to use  `previouslyUnreleased`.

Since nothing is done in `perform`, I suppose thats a quite crucial api.

**Comment by matthias-reis** [comment]
`previouslyUnreleased` is a data entity in the package.json, that is written in the `pre` step and consumed in the `perform` step. So it usually is automatically created.

I think this should be added to the documentation to be clarified.

**Comment by Xiphe** [comment]
according to what we talked about today, I consider this as internal API and am fine with not documenting it. Feel free to close this issue if you like.
