### ISSUE TITLE
As a package consumer I want background and context for changes

### ISSUE THREAD

**Issue by Xiphe** [matthias-reis/rlsr#6]
When I read the changelog of a package

Then I expect to find all relevant informations for me, for example

 - migration guidelines for Breaking changes
 - reasoning for reverts
 - design decisions that lead to features
 - ...

But most of these informations can usually be found in the commit body 
And I can't find this information within the generated `changelog.md` files

---

This could be solved by adding the body to the changelog or adding links to the single commits.

**Comment by matthias-reis** [comment]
Changelog format:


# Changelog rlsr-1-1

## Version 1.1.0

patch fix: **patch**
> something more
> closes #14

minor feat: **minor change**
> This is the body
> 
> And the footer

Dependency update of *rlsr-1-1-1* (feat): **small change**


## Version 1.0.3

Dependency update of *rlsr-1-1-1* (feat): new stuff BREAKING

## Version 1.0.2

Dependency update of *rlsr-1-1-1* (feat): new stuff BREAKING

## Version 1.0.1

Dependency update of *rlsr-1-1-1* (feat): new stuff BREAKING
